var group=["组一","组二","组三"];
var allData=[
    {
        name:"组一",
        data:[
            {
                date:"2018-1-12",
                list:[
                    {
                        stage:"1",
                        status:""
                    },
                    {
                        stage:"2",
                        status:""
                    },
                    {
                        stage:"3",
                        status:""
                    },
                    {
                        stage:"45",
                        status:"false"
                    },
                    {
                        stage:"46",
                        status:"false"
                    }
                ]
            }
        ]
    },
    {
        name:"组二",
        data:[
            {
                date:"2018-1-12",
                list:[
                    {
                        stage:"45",
                        status:"true"
                    },
                    {
                        stage:"46",
                        status:"true"
                    }
                ]
            },
            {
                date:"2018-1-13",
                list:[
                    {
                        stage:"1",
                        status:"true"
                    },
                    {
                        stage:"45",
                        status:"true"
                    },
                    {
                        stage:"46",
                        status:"true"
                    }
                ]
            }
        ]
    },
    {
        name:"组三",
        data:[
            {
                date:"2018-1-12",
                list:[
                    {
                        stage:"45",
                        status:"false"
                    },
                    {
                        stage:"46",
                        status:"true"
                    }
                ]
            }
        ]
    },

];